   # Feed Forward Neural Networks

In [35]:
from IPython.display import Image
%matplotlib inline

# implement a multilayer perceptron

In [36]:
import numpy as np
import sys

class NeuralNetMLP(object):
    def __init__(self, input_size, hidden_size, output_size):
        # Initialize weights with random values
        self.weights_input_hidden = 2 * np.random.random((input_size, hidden_size)) - 1
        self.weights_hidden_output = 2 * np.random.random((hidden_size, output_size)) - 1

    def sigmoid(x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(x):
        return x * (1 - x)

    def feedforward(self, inputs):
        # Input to hidden layer
        hidden_inputs = np.dot(inputs, self.weights_input_hidden)
        hidden_outputs = self.sigmoid(hidden_inputs)

        # Hidden to output layer
        final_inputs = np.dot(hidden_outputs, self.weights_hidden_output)
        final_outputs = self.sigmoid(final_inputs)

        return final_outputs
    
    def train(self, training_inputs, training_outputs, epochs):
        for epoch in range(epochs):
            # Forward pass
            hidden_inputs = np.dot(training_inputs, self.weights_input_hidden)
            hidden_outputs = self.sigmoid(hidden_inputs)

            final_inputs = np.dot(hidden_outputs, self.weights_hidden_output)
            final_outputs = self.sigmoid(final_inputs)

            # Calculate errors
            output_errors = training_outputs - final_outputs
            hidden_errors = np.dot(output_errors, self.weights_hidden_output.T)

            # Backpropagation
            output_delta = output_errors * self.sigmoid_derivative(final_outputs)
            hidden_delta = hidden_errors * self.sigmoid_derivative(hidden_outputs)

            # Update weights
            self.weights_hidden_output += np.dot(hidden_outputs.T, output_delta)
            self.weights_input_hidden += np.dot(training_inputs.T, hidden_delta)


In [37]:
if __name__ == "__main__":
    # Example usage
    input_size = 3
    hidden_size = 4
    output_size = 1

    neural_network = NeuralNetMLP(input_size, hidden_size, output_size)

    # Example training data (XOR problem)
    training_inputs = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
    training_outputs = np.array([[0, 1, 1, 0]]).T



In [38]:
    print("Random starting weights:")
    print("Input to Hidden weights:\n", neural_network.weights_input_hidden)
    print("Hidden to Output weights:\n", neural_network.weights_hidden_output)

    print("Training the neural network...")
    neural_network.train(training_inputs, training_outputs, epochs=10000)

    print("\nTrained weights:")
    print("Input to Hidden weights:\n", neural_network.weights_input_hidden)
    print("Hidden to Output weights:\n", neural_network.weights_hidden_output)
    # Test the network
    new_input = np.array([1, 0, 0])
    prediction = neural_network.feedforward(new_input)
    print("\nTesting the network with input [1, 0, 0]:")
    print("Prediction:", prediction)

Random starting weights:
Input to Hidden weights:
 [[-0.96638537  0.82725112 -0.23187788 -0.08556792]
 [ 0.85529728 -0.97645457 -0.54886329 -0.62967491]
 [-0.11466459  0.40809187  0.33094219 -0.22488717]]
Hidden to Output weights:
 [[ 0.23510529]
 [-0.20208438]
 [ 0.61039997]
 [ 0.93149068]]
Training the neural network...


TypeError: NeuralNetMLP.sigmoid() takes 1 positional argument but 2 were given